[package]
name = "jb-name-proxy"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"]}
certify = "0.5.2"
third-wheel = { git = "https://github.com/floppydiskette/third-wheel" }
log = "0.4.17"
env_logger = "0.10.0"